const mongoose = require("mongoose");
const generalDetails = require("./generalDetails");

const subTypeMusicalInstrument = [
  " כלי מיתר",
  " כלי הקשה ותופים",
  " מגבר",
  " אורגן",
  " פסנתר",
  " כלי נשיפה",
  " קלידים",
  " ספרי תווים",
  " אקורדיון",
  " אביזרים נלווים",
  " אחר",
];
const subTypeTools = [
  " חומרי עבודה",
  " כלי עבודה",
  " כלי עבודה לגינה",
  " כלים לנגרות",
  " כלים לעבודת מכונאות",
  " כלים לשרברבות",
  " גנרטורים",
  " אחר",
];
const subTypeToHome = [
  " ארגזי אחסון",
  " בלוני גז",
  " בר מים",
  " ברזים",
  " דוד חימום",
  " הרחקת מזיקים",
  " וילונות",
  " חימום על גז",
  " חימום על סולר",
  " חלונות ותריסים",
  " חפצי נוי",
  " טאבון",
  " ידיות",
  " כיורים",
  " כלי אוכל",
  " כלי מיטה",
  " כלי עבודה",
  " כספת",
  " כריות נוי",
  " לאמבטיה ולשירותים",
  " למטבח",
  " מדרגות מתקפלות",
  " מטהרי אוויר לבית",
  " מכשירי סודה",
  " מנגל",
  " מקלחונים",
  " משקל",
  " מתקן ייבוש כלים",
  " מתקן עיתונים",
  " סולמות",
  " סורגים",
  " סכו''ם",
  " עגלת קניות",
  " עיצוב הבית ואביזרים",
  " פאנלים סולאריים",
  " פחי אשפה",
  " פרקטים",
  " קולבים",
  " קמין",
  " קרש גיהוץ",
  " ריצוף וחיפוי",
  " תמונות",
  " תנור נפט",
  "אחר",
];
const subTypeToGarden = [
  " ברזנטים",
  " בריכה",
  " חפצי נוי",
  " כלי עבודה",
  " מחסן",
  " מכסחת דשא",
  " ממטרות ומערכות השקיה",
  " מנגל",
  " נדנדות וערסל",
  " סוכות",
  " עצי זית עתיקים",
  " עצים ועציצים",
  " פרגולות",
  " צמחיה מלאכותית",
  " ריהוט לגינה",
  " תאורת גן",
  " אחר",
];
const subTypeAppliances = [
  " DVD",
  " אופה לחם",
  " בלנדר ומיקסר",
  " וידאו",
  " זרוע לטלוויזיה",
  " טוחן אשפה",
  " טוסטר",
  " טוסטר אובן",
  " טלויזיה",
  " טלפונים ואביזרים",
  " כיריים",
  " מאוורר",
  " מגהץ",
  " מדיח כלים",
  " מזגן",
  " מחברים וכבלים",
  " מטחנת בשר",
  " מטחנת קפה",
  " מטען לסוללות",
  " מיחם לשבת",
  " מייבש כביסה",
  " מיקרוגל",
  " מכונת גלידה",
  " מכונת כביסה",
  " מכונת קפה",
  " מכונת תפירה",
  " מכשירי פקס",
  " מנגל",
  " מסחטה",
  " מעבד מזון",
  " מפזר חום",
  " מקפיא",
  " מקרן",
  " מקרר",
  " מקרר יינות",
  " מקרר מיני בר",
  " מתקני / מטהרי מים",
  " ניקוי בקיטור",
  " סדין חשמלי",
  " סטרימר",
  " סיר בישול",
  " סיר טיגון",
  " פלטה חשמלית",
  "אחר",
];
const subTypeComputersAndRelatedEquipment = [
  " מחשב נייד",
  " טאבלטים",
  " מסכי מחשב",
  " Ebook Reader",
  " google glass",
  " אביזרים",
  " אייפד אייר 2 ipad air",
  " אייפד אייר 3 iPad Air",
  " אייפד אייר ipad air",
  " אייפד מיני iPad mini",
  " אייפד מיני iPad mini 2",
  " אייפד מיני iPad mini 3",
  " אייפד מיני iPad mini 4",
  " אייפד פרו iPad Pro 9.7",
  " אייפד פרו iPadPro",
  " אייפד1 iPad1",
  " אייפד2 iPad2",
  " אייפד3 iPad3",
  " אייפד4 iPad4",
  " אייפד5 iPad5\t",
  " חומרה",
  " מדפסות",
  " מחשב כף יד",
  " מחשב שולחני",
  " מילון אלקטרוני",
  " משחקי מחשב",
  " ניווט GPS",
  " סורקים",
  " עט דיגיטלי",
  " צורבים",
  " שרתים",
  " תוכנות",
  " אחר",
];
const subTypeCellular = [
  " מכשיר סלולרי",
  " אביזרים",
  " כרטיס סים",
  " מודם סלולרי",
  " מספרי זהב",
  " Smartwatch",
  " אחר",
];

const generalProductsSchema = new mongoose.Schema(
  {
    category:{type:String ,default:"מוצרים",immutable:true},
    type: {
      type: String,
      required: true,
      enum: [
        "כלי נגינה",
        "כלי עבודה",
        "לבית",
        "לגינה",
        "לתינוק ולילד",
        "מוצרי חשמל",
        "מחשבים וציוד נלווה",
        "סלולרי",
        "אחר",
      ],
    },
    Subtype: {
      type: String,
      validate: {
        validator: function (val) {
          if (this.type === "כלי נגינה")
            return isValInArray(subTypeMusicalInstrument, val);
          if (this.type === "כלי עבודה") return isValInArray(subTypeTools, val);
          if (this.type === "לבית") return isValInArray(subTypeToHome, val);
          if (this.type === "לגינה") return isValInArray(subTypeToGarden, val);
          if (this.type === "מוצרי חשמל")
            return isValInArray(subTypeAppliances, val);
          if (this.type === "מחשבים וציוד נלווה")
            return isValInArray(subTypeComputersAndRelatedEquipment, val);
          if (this.type === "סלולרי") return isValInArray(subTypeCellular, val);
          if (this.type === "אחר") return true;
          return false;
        },
        message: (props) => `${props.value} is not a valid subtype!`,
      },
    },
    status: {
      type: String,
      required: true,
      enum: ["חדש באריזה", "כמו חדש", "משומש", "דרוש תיקון"],
    },
    manufacturer: String,
    nameOfProduct: String,
    ...generalDetails,
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
  }
);

module.exports = new mongoose.model("general_products", generalProductsSchema);
